

min_length: 5
max_length: 25
max_depth: 4
max_child: 100
t_extract : 0.65
t_aggregate: 0.65
t_feedback: 0
regex: # the regex order is important: The first must be timestame and the last must be splitter
  -
    name: header
    re: '\[[0-9]{2}:[0-9]{2}:[0-9]{2}\]'
    symbol: <!>
  - 
    name: dir
    re: '(([A-Z]:)|)(/\S+)+'
    symbol: <*dr>
  -
    name: url
    re: '(\S+\.\S+(\.\S+)+(:\d+)?)|(\w+-\w+(-\w+)+)'
    symbol: <*ul>
  -
    name: ip
    re: '(/|)([0-9]+\.){3}[0-9]+(:[0-9]+|)(:|)'
    symbol: <*ip>
  -
    name: int
    re: '(0x.*?\s)|(?<=[^A-Za-z0-9])(\-?\+?\d+)(?=[^A-Za-z0-9])|[0-9]+$'
    symbol: <*it>
  -
    name: bool
    re: '(=*|)(True)|(False)|(true)|(false)'
    symbol: <*bl>
  -
    name: unknown
    re: '[-\+\=\|]+'
    symbol: <?>